# Generated by Django 3.0.3 on 2020-11-15 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddedEntry',
            fields=[
                ('added_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_entry_name', models.CharField(blank=True, default='', max_length=255)),
                ('added_entry_type', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_isbn', models.CharField(blank=True, default='', max_length=13)),
                ('book_issn', models.CharField(blank=True, default='', max_length=9)),
                ('book_language', models.CharField(blank=True, default='', max_length=50)),
                ('book_lc_callno', models.CharField(blank=True, default='', max_length=50)),
                ('book_ddc_callno', models.CharField(blank=True, default='', max_length=50)),
                ('book_edition', models.CharField(blank=True, default='', max_length=255)),
                ('book_note_gen', models.TextField(blank=True, default='')),
                ('book_note_bib', models.TextField(blank=True, default='')),
                ('book_note_contents', models.TextField(blank=True, default='')),
                ('added_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='booknest.AddedEntry')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('holding_id', models.AutoField(primary_key=True, serialize=False)),
                ('holding_units', models.TextField(blank=True, default='')),
                ('holding_supplements', models.TextField(blank=True, default='')),
                ('holding_indexes', models.TextField(blank=True, default='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='booknest.Book')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='booknest.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainEntry',
            fields=[
                ('main_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_entry_name', models.CharField(blank=True, default='', max_length=255)),
                ('main_entry_role', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalDescription',
            fields=[
                ('physical_id', models.AutoField(primary_key=True, serialize=False)),
                ('physical_extent', models.CharField(blank=True, default='', max_length=100)),
                ('physical_details', models.CharField(blank=True, default='', max_length=100)),
                ('physical_dimensions', models.CharField(blank=True, default='', max_length=100)),
                ('physical_accomp_mats', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.AutoField(primary_key=True, serialize=False)),
                ('publication_place', models.CharField(blank=True, default='', max_length=100)),
                ('publication_name', models.CharField(blank=True, default='', max_length=100)),
                ('publication_date', models.CharField(blank=True, default='', max_length=50)),
                ('copyright_date', models.CharField(blank=True, default='', max_length=50)),
                ('current_publication_freq', models.CharField(blank=True, default='', max_length=100)),
                ('previous_publication_freq', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('series_name', models.CharField(blank=True, default='', max_length=255)),
                ('series_vol_num', models.CharField(blank=True, default='', max_length=50)),
                ('series_issn', models.CharField(blank=True, default='', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_added', models.CharField(blank=True, default='', max_length=255)),
                ('subject_added_type', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_title', models.CharField(max_length=255, unique=True)),
                ('work_title_var', models.CharField(blank=True, default='', max_length=255)),
                ('main_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='booknest.MainEntry')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_barcode', models.IntegerField(blank=True, default='')),
                ('item_callno', models.CharField(blank=True, default='', max_length=50)),
                ('item_copy', models.IntegerField(blank=True, default='')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='booknest.Holding')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='physical_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='booknest.PhysicalDescription'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='booknest.Publication'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='booknest.Series'),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='booknest.Subject'),
        ),
        migrations.AddField(
            model_name='book',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='booknest.Work'),
        ),
    ]
