# Generated by Django 3.0.3 on 2020-11-15 05:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddedEntry',
            fields=[
                ('added_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_entry_name', models.CharField(max_length=255)),
                ('added_entry_date', models.CharField(blank=True, default='', max_length=255)),
                ('added_entry_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('added_entry_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Added Entry',
                'verbose_name_plural': 'Added Entries',
                'unique_together': {('added_entry_name', 'added_entry_date', 'added_entry_identifier', 'added_entry_type')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_isbn', models.CharField(blank=True, default='', max_length=13)),
                ('book_issn', models.CharField(blank=True, default='', max_length=9)),
                ('book_language', models.CharField(blank=True, default='', max_length=50)),
                ('book_lc_callno', models.CharField(blank=True, default='', max_length=50)),
                ('book_ddc_callno', models.CharField(blank=True, default='', max_length=50)),
                ('book_edition', models.CharField(blank=True, default='', max_length=255)),
                ('book_publication_place', models.CharField(blank=True, default='', max_length=100)),
                ('book_publication_name', models.CharField(blank=True, default='', max_length=100)),
                ('book_publication_date', models.CharField(blank=True, default='', max_length=50)),
                ('book_copyright_date', models.CharField(blank=True, default='', max_length=50)),
                ('book_current_publication_freq', models.CharField(blank=True, default='', max_length=100)),
                ('book_previous_publication_freq', models.CharField(blank=True, default='', max_length=100)),
                ('book_physical_extent', models.CharField(blank=True, default='', max_length=100)),
                ('book_physical_details', models.CharField(blank=True, default='', max_length=100)),
                ('book_physical_dimensions', models.CharField(blank=True, default='', max_length=100)),
                ('book_accompanying_materials', models.CharField(blank=True, default='', max_length=100)),
                ('book_note_gen', models.TextField(blank=True, default='')),
                ('book_note_bib', models.TextField(blank=True, default='')),
                ('book_note_contents', models.TextField(blank=True, default='')),
                ('book_series_vol_num', models.CharField(blank=True, default='', max_length=50)),
                ('added_entry', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='booknest.AddedEntry')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('holding_id', models.AutoField(primary_key=True, serialize=False)),
                ('holding_units', models.TextField(blank=True, default='')),
                ('holding_supplements', models.TextField(blank=True, default='')),
                ('holding_indexes', models.TextField(blank=True, default='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='booknest.Book')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='booknest.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainEntry',
            fields=[
                ('main_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_entry_name', models.CharField(max_length=255)),
                ('main_entry_date', models.CharField(blank=True, default='', max_length=255)),
                ('main_entry_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('main_entry_role', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Main Entry',
                'verbose_name_plural': 'Main Entries',
                'unique_together': {('main_entry_name', 'main_entry_date', 'main_entry_identifier', 'main_entry_role')},
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('series_title', models.CharField(max_length=255)),
                ('series_date', models.CharField(blank=True, default='', max_length=255)),
                ('series_author', models.CharField(blank=True, default='', max_length=255)),
                ('series_author_date', models.CharField(blank=True, default='', max_length=255)),
                ('series_author_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('series_issn', models.CharField(blank=True, default='', max_length=9)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_title', models.CharField(max_length=255)),
                ('work_title_var', models.CharField(blank=True, default='', max_length=255)),
                ('main_entry', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='works', to='booknest.MainEntry')),
            ],
            options={
                'unique_together': {('work_title', 'main_entry')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_added', models.CharField(max_length=255)),
                ('subject_added_subfield1', models.CharField(blank=True, default='', max_length=255)),
                ('subject_added_subfield2', models.CharField(blank=True, default='', max_length=255)),
                ('subject_added_subfield3', models.CharField(blank=True, default='', max_length=255)),
                ('subject_added_subfield4', models.CharField(blank=True, default='', max_length=255)),
                ('subject_added_type', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('subject_added', 'subject_added_subfield1', 'subject_added_subfield2', 'subject_added_subfield3', 'subject_added_subfield4', 'subject_added_type')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_barcode', models.IntegerField(blank=True, default='')),
                ('item_callno', models.CharField(blank=True, default='', max_length=50)),
                ('item_copy', models.IntegerField(blank=True, default='')),
                ('item_owner', models.CharField(blank=True, default='', max_length=255)),
                ('item_receiving_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('item_enum_a', models.CharField(blank=True, default='', max_length=255)),
                ('item_enum_b', models.CharField(blank=True, default='', max_length=255)),
                ('item_enum_c', models.CharField(blank=True, default='', max_length=255)),
                ('item_chron_i', models.CharField(blank=True, default='', max_length=255)),
                ('item_chron_j', models.CharField(blank=True, default='', max_length=255)),
                ('item_chron_k', models.CharField(blank=True, default='', max_length=255)),
                ('item_description', models.CharField(blank=True, default='', max_length=255)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='booknest.Holding')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='booknest.Location'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='booknest.Series'),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='booknest.Subject'),
        ),
        migrations.AddField(
            model_name='book',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='booknest.Work'),
        ),
    ]
