# Generated by Django 3.0.3 on 2020-11-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booknest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addedentry',
            options={'ordering': ['added_entry_name', 'added_entry_date', 'added_entry_identifier'], 'verbose_name': 'Added Entry', 'verbose_name_plural': 'Added Entries'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['work']},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['location', 'collection_name']},
        ),
        migrations.AlterModelOptions(
            name='holding',
            options={'ordering': ['book', 'collection']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['holding', 'item_description', 'item_copy']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name']},
        ),
        migrations.AlterModelOptions(
            name='mainentry',
            options={'ordering': ['main_entry_name', 'main_entry_date', 'main_entry_identifier'], 'verbose_name': 'Main Entry', 'verbose_name_plural': 'Main Entries'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['series_title', 'series_date', 'series_author', 'series_author_date', 'series_author_identifier'], 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_added', 'subject_added_subfield1', 'subject_added_subfield2', 'subject_added_subfield3', 'subject_added_subfield4']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['work_title', 'main_entry']},
        ),
    ]
