# Generated by Django 3.0.3 on 2020-11-15 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booknest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addedentry',
            options={'verbose_name': 'Added Entry', 'verbose_name_plural': 'Added Entries'},
        ),
        migrations.AlterModelOptions(
            name='mainentry',
            options={'verbose_name': 'Main Entry', 'verbose_name_plural': 'Main Entries'},
        ),
        migrations.AlterModelOptions(
            name='physicaldescription',
            options={'verbose_name': 'Physical Description', 'verbose_name_plural': 'Physical Descriptions'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
    ]
