# Generated by Django 3.0.3 on 2020-11-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booknest', '0002_auto_20201115_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='booknest.AddedEntry'),
        ),
    ]
