# Generated by Django 3.0.3 on 2020-11-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booknest', '0003_auto_20201115_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='booknest.Series'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='booknest.Subject'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='booknest.Location'),
        ),
        migrations.AlterField(
            model_name='work',
            name='main_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='works', to='booknest.MainEntry'),
        ),
    ]
