# Generated by Django 3.0.3 on 2020-11-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booknest', '0004_auto_20201115_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_barcode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_copy',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
