# Generated by Django 3.0.3 on 2020-11-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booknest', '0005_auto_20201115_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_receiving_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
